In [29]:
import itertools
from time import sleep
import numpy as np
import os
import pandas as pd
import re
import pathlib
import csv
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from sklearn.metrics import accuracy_score, f1_score, recall_score
from sklearn.metrics import precision_score
import shutil
import soundfile as sf
import matplotlib.pyplot as plt
import librosa
from pathlib import Path
import keyboard

In [30]:
DATASET_ROOT = os.path.join(os.path.expanduser("~"),'dataSet/audio/agender_distribution/')
NETWORK_ROOT = os.path.join(os.path.expanduser("~"),'Mestrado-PC/github/Conv1D/CNN/')

In [31]:
# pause() function definition.
def pause():
	while True:
		if keyboard.read_key() == 'space':
			# If you put 'space' key
			# the program will resume.
			break

In [32]:
def audio_to_fft(audio):
    # Since tf.signal.fft applies FFT on the innermost dimension, we need to squeeze the dimensions and then expand them again after FFT
    audio = tf.squeeze(audio, axis=-1)
    fft = tf.signal.fft(tf.cast(tf.complex(real=audio, imag=tf.zeros_like(audio)), tf.complex64))
    fft = tf.expand_dims(fft, axis=-1)
    # Return the absolute value of the first half of the FFT which represents the positive frequencies
    return tf.math.abs(fft[:, : (audio.shape[1] // 2), :])

In [33]:
def path_to_audio(path):
    # Reads and decodes an audio file
    audio = tf.io.read_file(path)
    audio, _ = tf.audio.decode_wav(audio, 1, 8000)
    return audio

In [34]:
def paths_and_labels_to_dataset(audio_paths, labels):
    # Constructs a dataset of audios and labels
    path_ds = tf.data.Dataset.from_tensor_slices(audio_paths)
    audio_ds = path_ds.map(lambda x: path_to_audio(x))
    label_ds = tf.data.Dataset.from_tensor_slices(labels)
    return tf.data.Dataset.zip((audio_ds, label_ds))

In [35]:
def map_func(npy_path):
    npy_content = np.load(npy_path)
    return npy_content

In [36]:
def paths_and_labels_to_dataset_HTK(paths, labels):
    path_ds = tf.data.Dataset.from_tensor_slices(paths)
    array_ds = path_ds.map(lambda x: tf.numpy_function(map_func, [x], tf.float64),num_parallel_calls=tf.data.experimental.AUTOTUNE)
    label_ds = tf.data.Dataset.from_tensor_slices(labels)
    return tf.data.Dataset.zip((array_ds, label_ds))

In [37]:
def npy_header_offset(npy_path):
    with open(str(npy_path), 'rb') as f:
        if f.read(6) != b'\x93NUMPY':
            raise ValueError('Invalid NPY file.')
        version_major, version_minor = f.read(2)
        if version_major == 1:
            header_len_size =2
        elif version_major == 2:
            header_len_size = 4
        else:
            raise ValueError('Unknown NPY file version {}.{}.'.format(version_major, version_minor))
        header_len = sum(b << (8 * i) for i, b in enumerate(f.read(header_len_size)))
        header = f.read(header_len)
        if not header.endswith(b'\n'):
            raise ValueError('Invalid NPY file.')
        return f.tell()

In [74]:
train_file_list_path = 'file_lists/HTK-FFT/train_database_sorted2.csv'
test_file_list_path = 'file_lists/HTK-FFT/test_database_sorted2.csv'

In [75]:
train_file_list = pd.read_csv(os.path.join(NETWORK_ROOT, train_file_list_path))
train_audio_files = train_file_list['file']
train_classes = train_file_list['class']

In [79]:
audio_paths = list(train_audio_files)
labels = list(train_classes)

In [41]:
for i in range(len(audio_paths)):
    audio_paths[i] = re.sub('.wav', '-n.mfc.csv', audio_paths[i])

In [102]:
for i in range(len(audio_paths)):
    audio_paths[i] = re.sub('-n.npy', '-n.wav', audio_paths[i])

In [93]:
for i in range(len(audio_paths)):
    audio_paths[i] = os.path.join(DATASET_ROOT, audio_paths[i])

In [ ]:
train_ds = paths_and_labels_to_dataset_HTK(audio_paths, labels)
train_ds_fft = paths_and_labels_to_dataset(audio_paths, labels)

In [100]:
path_ds = tf.data.Dataset.from_tensor_slices(audio_paths)

In [ ]:
audio_paths

In [ ]:
for element in path_ds:
    a = tf.io.read_file(element)
    # b = tf.io.decode_raw(a, out_type=float, little_endian=False)
    print(element)
    print(a)
    '''b = tf.strings.to_number(tf.strings.split(a, sep=" "), tf.float64)
    print(type(b))
    print(b)'''
    input("Press any key to terminate the program")

In [45]:
npy_file = '/home/ferreiraa/dataSet/audio/agender_distribution/wav_traindevel/1006/1/a11006s14-n.npy'

In [46]:
num_features = 1170
dtype = tf.float64

In [47]:
header_offset = npy_header_offset(npy_file)

In [48]:
header_offset

128

In [49]:
dataset = tf.data.FixedLengthRecordDataset([npy_file], num_features * dtype.size, header_bytes=header_offset)

In [ ]:
dataset = dataset.map(lambda s: tf.io.decode_raw(s, dtype))

In [50]:
dataset = dataset.map(lambda s: tf.reshape(tf.io.decode_raw(s, dtype), (num_features,)))

In [51]:
dataset

<MapDataset element_spec=TensorSpec(shape=(1170,), dtype=tf.float64, name=None)>

In [52]:
list(dataset.as_numpy_iterator())

[array([-2.108996e+01, -2.541953e+01, -2.317181e+01, ..., -5.002567e-02,
        -1.043014e-03,  5.149288e-02])]

In [53]:
dataset2 = tf.data.FixedLengthRecordDataset([npy_file], num_features * dtype.size, header_bytes=header_offset)

In [55]:
dataset2 = dataset2.map(lambda s: tf.reshape(tf.io.decode_raw(s, dtype), (num_features, 1)))

In [56]:
dataset2

<MapDataset element_spec=TensorSpec(shape=(1170, 1), dtype=tf.float64, name=None)>

In [57]:
list(dataset2.as_numpy_iterator())

[array([[-2.108996e+01],
        [-2.541953e+01],
        [-2.317181e+01],
        ...,
        [-5.002567e-02],
        [-1.043014e-03],
        [ 5.149288e-02]])]

In [95]:
element_dataset = tf.data.FixedLengthRecordDataset([audio_paths], num_features * dtype.size, header_bytes=header_offset)

In [96]:
element_dataset

<FixedLengthRecordDatasetV2 element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [97]:
audio_dataset = element_dataset.map(lambda s: tf.reshape(tf.io.decode_raw(s, dtype), (num_features, 1)))

In [98]:
audio_dataset

<MapDataset element_spec=TensorSpec(shape=(1170, 1), dtype=tf.float64, name=None)>

In [99]:
list(audio_dataset.as_numpy_iterator())

[array([[-2.108996e+01],
        [-2.541953e+01],
        [-2.317181e+01],
        ...,
        [-5.002567e-02],
        [-1.043014e-03],
        [ 5.149288e-02]]),
 array([[-1.342177e+01],
        [-8.199965e+00],
        [-4.861622e+00],
        ...,
        [ 9.349146e-02],
        [ 6.808297e-02],
        [ 3.530367e-03]]),
 array([[-13.65137  ],
        [-29.66002  ],
        [-24.57028  ],
        ...,
        [ -0.4184372],
        [ -0.1826239],
        [  0.3261425]]),
 array([[-1.345268e+01],
        [-1.648699e+01],
        [-1.635873e+01],
        ...,
        [-2.857000e-03],
        [ 1.857936e-04],
        [ 3.254887e-03]]),
 array([[-1.186642e+01],
        [ 2.608200e+00],
        [ 1.934733e+00],
        ...,
        [-9.494931e-03],
        [ 2.645722e-02],
        [ 3.704117e-02]]),
 array([[-16.68189  ],
        [-16.54376  ],
        [-15.9441   ],
        ...,
        [  0.1712335],
        [  0.2193936],
        [  0.1977948]]),
 array([[-11.57684  ],
        [-1

In [70]:
conteudo = pd.read_csv('/home/ferreiraa/dataSet/audio/agender_distribution/wav_traindevel/1006/4/a11006s18-n.mfc.csv', delimiter=' ', nrows=30, header=None)

In [71]:
conteudo

0          1          2          3          4          5   \
0   -8.770237  -2.376163  -0.795871  -6.620070 -15.358670  -5.479703   
1   -0.952211  11.607380 -11.035940 -17.626930 -21.215250 -17.936020   
2   -0.415939  14.790150 -11.982190 -18.915110 -15.921630 -16.521110   
3   -0.993454  14.448760 -14.554920 -13.986670 -20.986960 -11.227630   
4   -1.494640  14.155470 -18.197300  -9.979894 -17.224010  -7.972981   
5   -3.441280  11.083140 -23.075160 -14.178530 -11.892170 -11.144520   
6   -5.352982   7.696323 -28.386730 -24.843120  -3.005089 -15.082220   
7   -8.635302   3.197315 -25.436740 -21.776440   5.825172 -13.312120   
8  -12.105400  -5.573937 -18.615990 -19.489400   8.756953 -12.159500   
9  -15.806020 -10.460080  -9.964294 -10.882230   3.898700  -6.164186   
10 -17.709290 -21.272400  -4.879855 -14.686340   2.131762 -14.056960   
11 -13.094650 -24.355360  -0.532666  -6.510877   5.852286  -8.981412   
12 -12.256150 -23.502750   1.182611  -0.866651   4.048465  -3.956391   
13  -7.829183 -13.308230   1.478025   2.267233   7.349949  -8.691613   
14 -10.838920 -13.044640  -1.566613   2.681555  -8.086147  -6.601074   
15 -15.651240  -5.288826  -5.723466   2.178778  -3.266412  -6.654780   
16 -16.910300  -7.281872 -10.299140  -2.853511  -5.252839  -3.362446   
17 -15.585790  -5.137617  -9.374393  -1.869707  -4.242884   0.152986   
18 -15.125720  -3.410626  -4.935298  -0.021167  -3.718815   0.963580   
19 -15.100460  -3.816736  -2.765753  -0.969475  -6.991069  -2.144907   
20 -14.166770  -3.093837  -1.887587   1.793240  -8.476291  -0.012747   
21 -14.894020  -3.573191  -7.006132  -3.128894  -5.192616  -4.496566   
22 -13.737260  -0.576110  -5.125862   1.781687  -3.289663  -2.257807   
23 -15.399340  -5.155554  -9.651785  -4.709852  -2.072460  -2.904885   

           6          7          8          9   ...        29        30  \
0   -4.583696  -0.083572  -6.248782  -8.495719  ...  0.736038  0.021232   
1   -0.328501 -14.561820   4.411447 -21.195700  ...  1.353755  0.521327   
2   -4.894401 -10.273530   3.474319 -17.824730  ...  0.899584  1.129841   
3    2.249686 -12.629250  -2.316049 -21.359050  ... -0.157975  1.977557   
4    7.883900 -17.290250   3.661576 -14.382120  ... -0.933498  1.968627   
5    7.653436 -13.184720   3.490082 -20.864600  ... -0.223404  0.867514   
6    9.585992 -15.961370   0.368256 -18.598480  ...  1.289004 -0.776607   
7    8.303496 -15.647250  -4.376194 -17.139350  ...  1.893786 -2.101603   
8    1.265155 -14.765550  -3.798175  -5.676677  ...  1.598554 -2.042001   
9  -11.272570  -8.182781  -3.324851  -1.712164  ...  0.667536 -0.848598   
10 -11.529300 -11.361190  -0.445001  -5.882155  ...  0.293967 -0.391806   
11  -7.865830  -8.598598  14.668470  -7.343381  ... -0.269163 -0.590769   
12  -0.353387 -10.421380  19.393090  -7.918958  ... -1.105491 -0.827024   
13  -4.226295  -4.417246  16.420420  -1.683649  ... -1.554312 -0.686239   
14  -5.503832  -1.201326   5.690205  -7.785865  ... -1.406721  0.634123   
15  -1.701992   0.228292   2.143123  -1.537752  ... -0.541751  0.858906   
16 -11.016520  -5.018322  -6.955729  -3.714505  ...  0.388566  0.544848   
17  -0.853870   0.851758  -4.285564  -5.038043  ...  0.458576  0.104375   
18  -6.993219  -1.637531   0.773302  -9.007586  ...  0.245606 -0.109445   
19  -5.358208  -5.601379   0.373521  -6.887921  ... -0.168037  0.537301   
20  -7.299531   2.900791   2.790716  -1.391521  ... -0.563501  0.719266   
21  -2.601356  -2.300398  -5.644089  -4.403033  ... -0.339324  0.415000   
22  -6.334137  -5.273718  -3.481527  -0.395133  ... -0.243606  0.020352   
23  -9.495939  -5.279076  -0.663606  -5.379649  ...  0.006114 -0.236030   

          31        32        33        34        35        36        37  \
0   0.845238  0.574815  0.043316 -0.465443  0.351460  0.631143  0.310012   
1   1.496014  0.740964  0.635687 -0.805370  0.903474  0.931309  1.494990   
2   1.196684  0.768476  0.768728 -0.802689  0.997704  0.877035  2.213919   
3   0.237571  0.077585  0.8169

In [104]:
path_ds = tf.data.Dataset.from_tensor_slices(audio_paths)

In [106]:
audio_ds = path_ds.map(lambda x: path_to_audio(x))

In [108]:
audio_ds

<MapDataset element_spec=TensorSpec(shape=(8000, 1), dtype=tf.float32, name=None)>

In [109]:
audio_dataset

<MapDataset element_spec=TensorSpec(shape=(1170, 1), dtype=tf.float64, name=None)>